name: pull request with dockerfile

on:
  pull_request:
    paths:
      - Dockerfile

jobs:
  format:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0
      - run: docker-compose build
      - run: docker-compose run --rm base make format
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0
      - run: docker-compose build
      - run: docker-compose run --rm base make test
