name: tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0
      - run: docker login docker.pkg.github.com -u r7kamura -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        env:
          GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
      - run: docker-compose pull
      - run: docker-compose run --rm base make format

  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0
      - run: docker login docker.pkg.github.com -u r7kamura -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        env:
          GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
      - run: docker-compose pull
      - run: docker-compose run --rm base make test
