name: without dockerfile

on:
  pull_request:
    paths-ignore:
      - Dockerfile
  push:
    branches:
      - master
    paths-ignore:
      - Dockerfile

jobs:
  format:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0
      - run: docker login docker.pkg.github.com -u dummy -p "${GITHUB_TOKEN}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: docker-compose pull
      - run: docker-compose run --rm base make format
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0
      - run: docker login docker.pkg.github.com -u dummy -p "${GITHUB_TOKEN}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: docker-compose pull
      - run: docker-compose run --rm base make test
